import random

AVAILABLE_ROLES = [
    "Software Engineer",
    "Data Analyst",
    "Data Scientist",
    "Frontend Developer",
    "Backend Developer",
    "Full Stack Developer",
    "Machine Learning Engineer",
    "DevOps Engineer",
    "Product Manager",
    "Business Analyst",
    "Java Developer",
    "Python Developer",
]

QUESTION_BANK = {
    "Software Engineer": [
        "Tell me about yourself and your experience as a software engineer.",
        "What is Object-Oriented Programming? Explain its four pillars.",
        "Explain the difference between a stack and a queue.",
        "What is the time complexity of binary search and why?",
        "How do you approach debugging a complex bug in production?",
        "Explain the concept of REST APIs and their best practices.",
        "What is version control and how do you use Git in your workflow?",
        "Describe a challenging project you worked on and how you solved it.",
        "What is the difference between SQL and NoSQL databases?",
        "How do you ensure code quality in your projects?",
    ],
    "Data Analyst": [
        "Tell me about yourself and your experience in data analysis.",
        "What is the difference between INNER JOIN, LEFT JOIN, and RIGHT JOIN in SQL?",
        "How do you handle missing data in a dataset?",
        "Explain the difference between mean, median, and mode.",
        "What tools do you use for data visualization and why?",
        "Describe a data analysis project that had a significant business impact.",
        "What is A/B testing and when would you use it?",
        "How do you communicate complex data insights to non-technical stakeholders?",
        "Explain what a pivot table is and when you use it.",
        "What is the difference between correlation and causation?",
    ],
    "Data Scientist": [
        "Tell me about yourself and your data science background.",
        "What is the bias-variance tradeoff in machine learning?",
        "Explain the difference between supervised and unsupervised learning.",
        "How do you handle class imbalance in a classification problem?",
        "What evaluation metrics do you use for regression vs classification?",
        "Explain overfitting and how you prevent it.",
        "What is cross-validation and why is it important?",
        "Describe a machine learning project you built end-to-end.",
        "What is feature engineering and why is it important?",
        "How do you choose between different machine learning algorithms?",
    ],
    "Frontend Developer": [
        "Tell me about yourself and your frontend development experience.",
        "What is the difference between CSS Flexbox and CSS Grid?",
        "Explain how the Virtual DOM works in React.",
        "What are React hooks and why were they introduced?",
        "How do you optimize a web application's performance?",
        "Explain the concept of responsive design.",
        "What is the difference between localStorage and sessionStorage?",
        "How do you handle state management in large React applications?",
        "What are Web Accessibility (a11y) best practices?",
        "Describe a challenging UI component you built.",
    ],
    "Backend Developer": [
        "Tell me about yourself and your backend development experience.",
        "Explain RESTful API design principles.",
        "What is the difference between authentication and authorization?",
        "How do you design a scalable database schema?",
        "What is caching and when would you use Redis?",
        "Explain microservices architecture and its pros and cons.",
        "How do you secure a REST API?",
        "What is the N+1 query problem and how do you solve it?",
        "Explain the concept of message queues like Kafka or RabbitMQ.",
        "Describe your experience with Docker and containerization.",
    ],
    "Machine Learning Engineer": [
        "Tell me about yourself and your ML engineering experience.",
        "What is the difference between a data scientist and an ML engineer?",
        "How do you deploy machine learning models to production?",
        "Explain MLOps and why it is important.",
        "What is model drift and how do you detect and handle it?",
        "Describe your experience with model serving frameworks.",
        "How do you monitor a deployed ML model?",
        "What is feature store and why is it important?",
        "Explain the concept of A/B testing for ML models.",
        "How do you handle latency requirements for real-time ML predictions?",
    ],
    "Full Stack Developer": [
        "Tell me about yourself and your full stack experience.",
        "Walk me through your typical development workflow for a new feature.",
        "How do you design a REST API and connect it to a frontend?",
        "What is CORS and how do you handle it?",
        "Explain the difference between server-side rendering and client-side rendering.",
        "How do you manage environment variables and secrets?",
        "Describe a full stack project you built from scratch.",
        "How do you handle database migrations in production?",
        "What is your approach to writing tests for full stack applications?",
        "How do you optimize both frontend and backend performance?",
    ],
    "DevOps Engineer": [
        "Tell me about yourself and your DevOps experience.",
        "Explain the CI/CD pipeline and how you have implemented one.",
        "What is the difference between Docker and Kubernetes?",
        "How do you monitor application health in production?",
        "Explain Infrastructure as Code and tools like Terraform.",
        "How do you handle zero-downtime deployments?",
        "What is the difference between horizontal and vertical scaling?",
        "How do you manage secrets and credentials securely?",
        "Describe an incident you handled and how you resolved it.",
        "What are the principles of Site Reliability Engineering?",
    ],
    "Product Manager": [
        "Tell me about yourself and your product management experience.",
        "How do you prioritize features on a product roadmap?",
        "Explain how you gather and validate user requirements.",
        "What metrics do you use to measure product success?",
        "Describe a product launch you led from ideation to release.",
        "How do you handle conflicting priorities between engineering and business?",
        "What is your process for writing a product requirements document?",
        "How do you work with engineering teams to define technical requirements?",
        "Describe a time a product decision you made turned out to be wrong.",
        "How do you conduct competitive analysis for a product?",
    ],
    "Business Analyst": [
        "Tell me about yourself and your business analysis experience.",
        "How do you gather requirements from stakeholders?",
        "What is the difference between functional and non-functional requirements?",
        "Describe your experience with process mapping and documentation.",
        "How do you handle scope creep in a project?",
        "Explain how you analyze data to derive business insights.",
        "What tools do you use for business analysis and project management?",
        "Describe a time you identified a problem and proposed a solution.",
        "How do you communicate technical findings to non-technical stakeholders?",
        "What is a use case diagram and when would you use one?",
    ],
    "Java Developer": [
        "Tell me about yourself and your Java development experience.",
        "Explain the concept of JVM, JRE, and JDK.",
        "What are the principles of SOLID in object-oriented design?",
        "How does garbage collection work in Java?",
        "Explain the difference between an interface and an abstract class in Java.",
        "What are Java Streams and how do you use them?",
        "Explain multithreading and synchronization in Java.",
        "What is Spring Boot and what problem does it solve?",
        "How do you handle exceptions in Java best practices?",
        "Describe a complex Java project you built.",
    ],
    "Python Developer": [
        "Tell me about yourself and your Python development experience.",
        "Explain Python's GIL and its implications for multithreading.",
        "What is the difference between a list and a tuple in Python?",
        "Explain Python decorators and give a practical example.",
        "What are Python generators and when would you use them?",
        "How do you manage Python dependencies and virtual environments?",
        "Explain the difference between deep copy and shallow copy.",
        "What is asyncio in Python and when would you use it?",
        "How do you write unit tests in Python using pytest?",
        "Describe a Python project where you used advanced features.",
    ],
}

COMMON_QUESTIONS = [
    "What are your greatest strengths and weaknesses?",
    "Where do you see yourself in 5 years?",
    "Why do you want to work for our company?",
    "Describe a time you worked under pressure and met a deadline.",
    "How do you handle disagreements with team members?",
]


def get_questions_for_role(role: str, count: int = 5) -> list:
    role_questions = QUESTION_BANK.get(role, QUESTION_BANK["Software Engineer"])
    selected = random.sample(role_questions, min(count - 1, len(role_questions)))
    common = random.sample(COMMON_QUESTIONS, 1)
    questions = selected + common
    random.shuffle(questions)
    return [{"id": i + 1, "text": q, "time_limit": 90} for i, q in enumerate(questions)]
